// Generated by Website Prompt Studio — interaction layer
document.addEventListener('DOMContentLoaded', function(){

// Supabase connection — project: mkwnlanpyfzbauampwtl
var supabaseClient = supabase.createClient(
  "https://mkwnlanpyfzbauampwtl.supabase.co",
  "PASTE_YOUR_PUBLISHABLE_KEY_HERE"
);

// mobile nav toggle
var navToggle = document.getElementById('navToggle');
var mainNav = document.getElementById('mainNav');
if(navToggle && mainNav){
navToggle.addEventListener('click', function(){ mainNav.classList.toggle('open'); });
mainNav.querySelectorAll('a').forEach(function(a){ a.addEventListener('click', function(){ mainNav.classList.remove('open'); }); });
}
// dark / light mode toggle (session only, no storage)
var themeToggle = document.getElementById('themeToggle');
if(themeToggle){
themeToggle.addEventListener('click', function(){
var root = document.documentElement;
var isDark = root.getAttribute('data-theme') === 'dark';
root.setAttribute('data-theme', isDark ? 'light' : 'dark');
themeToggle.textContent = isDark ? '🌙' : '☀️';
});
}
// scroll reveal
var revealEls = document.querySelectorAll('.reveal');
if('IntersectionObserver' in window && revealEls.length){
var io = new IntersectionObserver(function(entries){
entries.forEach(function(entry){ if(entry.isIntersecting){ entry.target.classList.add('in'); io.unobserve(entry.target); } });
}, { threshold: 0.15 });
revealEls.forEach(function(elm){ io.observe(elm); });
} else {
revealEls.forEach(function(elm){ elm.classList.add('in'); });
}
// simple demo audio player (progress bar only — wire up a real <audio> src to make it play)
document.querySelectorAll('[data-player]').forEach(function(player){
var btn = player.querySelector('[data-play]');
var fill = player.querySelector('.bar-fill');
var playing = false, pct = 0, timer = null;
btn.addEventListener('click', function(){
playing = !playing;
btn.textContent = playing ? '❚❚' : '▶';
if(playing){
timer = setInterval(function(){ pct = pct >= 100 ? 0 : pct + 1; fill.style.width = pct + '%'; }, 150);
} else { clearInterval(timer); }
});
});

// newsletter form — saves to Supabase table "newsletter_signups"
var nlForm = document.querySelector('[data-newsletter-form]');
if(nlForm){
nlForm.addEventListener('submit', function(e){
e.preventDefault();
var note = document.querySelector('[data-newsletter-note]');
var email = nlForm.querySelector('input[type=email]').value;
supabaseClient.from('newsletter_signups').insert({ email: email }).then(function(res){
if(res.error){
if(note) note.textContent = 'Something went wrong — please try again.';
console.error(res.error);
} else {
if(note) note.textContent = 'Thanks! You are on the list. 🎉';
nlForm.reset();
}
});
});
}

// contact form — saves to Supabase table "contact_messages"
var cForm = document.querySelector('[data-contact-form]');
if(cForm){
cForm.addEventListener('submit', function(e){
e.preventDefault();
var note = document.querySelector('[data-contact-note]');
var data = new FormData(cForm);
supabaseClient.from('contact_messages').insert({
name: data.get('name'),
email: data.get('email'),
message: data.get('message')
}).then(function(res){
if(res.error){
if(note) note.textContent = 'Something went wrong — please try again.';
console.error(res.error);
} else {
if(note) note.textContent = 'Thanks for reaching out — we will get back to you soon.';
cForm.reset();
}
});
});
}

});
